/**
 * Russian translations for Atomic CRM (ra-core + ra-supabase + resources + CRM UI).
 */
export const ru = {
  ra: {
    action: {
      add_filter: "Добавить фильтр",
      add: "Добавить",
      back: "Назад",
      bulk_actions: "Выбран 1 элемент |||| Выбрано элементов: %{smart_count}",
      cancel: "Отмена",
      clear_array_input: "Очистить список",
      clear_input_value: "Очистить значение",
      clone: "Клонировать",
      confirm: "Подтвердить",
      create: "Создать",
      create_item: "Создать %{item}",
      delete: "Удалить",
      edit: "Изменить",
      export: "Экспорт",
      list: "Список",
      refresh: "Обновить",
      remove_filter: "Убрать этот фильтр",
      remove_all_filters: "Убрать все фильтры",
      remove: "Удалить",
      reset: "Сбросить",
      save: "Сохранить",
      search: "Поиск",
      search_columns: "Поиск по столбцам",
      select_all: "Выбрать все",
      select_all_button: "Выбрать все",
      select_row: "Выбрать эту строку",
      show: "Просмотр",
      sort: "Сортировка",
      undo: "Отменить",
      unselect: "Снять выбор",
      expand: "Развернуть",
      close: "Закрыть",
      open_menu: "Открыть меню",
      close_menu: "Закрыть меню",
      update: "Обновить",
      move_up: "Поднять",
      move_down: "Опустить",
      open: "Открыть",
      toggle_theme: "Светлая/тёмная тема",
      select_columns: "Столбцы",
      update_application: "Перезагрузить приложение",
      reset_password: "Сбросить пароль",
    },
    boolean: {
      true: "Да",
      false: "Нет",
      null: " ",
    },
    page: {
      create: "Создать %{name}",
      dashboard: "Главная",
      edit: "%{name} %{recordRepresentation}",
      error: "Что-то пошло не так",
      list: "%{name}",
      loading: "Загрузка",
      not_found: "Не найдено",
      show: "%{name} %{recordRepresentation}",
      empty: "Пока нет %{name}.",
      invite: "Хотите добавить?",
      access_denied: "Доступ запрещён",
      authentication_error: "Ошибка аутентификации",
    },
    input: {
      file: {
        upload_several:
          "Перетащите файлы сюда или нажмите, чтобы выбрать.",
        upload_single: "Перетащите файл сюда или нажмите, чтобы выбрать.",
      },
      image: {
        upload_several:
          "Перетащите изображения сюда или нажмите, чтобы выбрать.",
        upload_single: "Перетащите изображение сюда или нажмите, чтобы выбрать.",
      },
      references: {
        all_missing: "Не удалось загрузить связанные данные.",
        many_missing:
          "По крайней мере одна из связей больше недоступна.",
        single_missing: "Связанная запись больше недоступна.",
      },
      password: {
        toggle_visible: "Скрыть пароль",
        toggle_hidden: "Показать пароль",
      },
    },
    message: {
      about: "О программе",
      access_denied: "Недостаточно прав для доступа к этой странице",
      are_you_sure: "Вы уверены?",
      authentication_error:
        "Сервер аутентификации вернул ошибку. Проверьте учётные данные.",
      auth_error: "Ошибка при проверке токена аутентификации.",
      bulk_delete_content:
        "Удалить этот %{name}? |||| Удалить выбранные %{smart_count} элементов?",
      bulk_delete_title: "Удалить %{name} |||| Удалить %{smart_count} %{name}",
      bulk_update_content:
        "Обновить %{name} %{recordRepresentation}? |||| Обновить %{smart_count} элементов?",
      bulk_update_title:
        "Обновить %{name} %{recordRepresentation} |||| Обновить %{smart_count} %{name}",
      clear_array_input: "Очистить весь список?",
      delete_content: "Удалить этот %{name}?",
      delete_title: "Удалить %{name} %{recordRepresentation}",
      details: "Подробнее",
      error: "Произошла ошибка. Запрос не выполнен.",
      invalid_form: "Проверьте форму на ошибки",
      loading: "Подождите",
      no: "Нет",
      not_found: "Неверная ссылка или страница не найдена.",
      select_all_limit_reached:
        "Слишком много элементов. Выбраны первые %{max}.",
      unsaved_changes:
        "Есть несохранённые изменения. Всё равно уйти?",
      yes: "Да",
      placeholder_data_warning: "Ошибка сети: не удалось обновить данные.",
    },
    navigation: {
      clear_filters: "Сбросить фильтры",
      no_filtered_results: "По фильтрам ничего не найдено.",
      no_results: "Ничего не найдено",
      no_more_results: "Страница %{page} недоступна.",
      page_out_of_boundaries: "Страница %{page} вне диапазона",
      page_out_from_end: "Нет следующей страницы",
      page_out_from_begin: "Нет предыдущей страницы",
      page_range_info: "%{offsetBegin}–%{offsetEnd} из %{total}",
      partial_page_range_info: "%{offsetBegin}–%{offsetEnd} из более чем %{offsetEnd}",
      current_page: "Страница %{page}",
      page: "Перейти на страницу %{page}",
      first: "В начало",
      last: "В конец",
      next: "Вперёд",
      previous: "Назад",
      page_rows_per_page: "Строк на странице:",
      skip_nav: "Перейти к содержимому",
      breadcrumb_drawer_title: "Путь",
      breadcrumb_drawer_instructions: "Укажите путь к странице",
    },
    sort: {
      sort_by: "Сортировка по %{field_lower_first} %{order}",
      ASC: "по возрастанию",
      DESC: "по убыванию",
    },
    auth: {
      auth_check_error: "Войдите, чтобы продолжить",
      user_menu: "Профиль",
      username: "Имя пользователя",
      password: "Пароль",
      email: "Email",
      sign_in: "Войти",
      sign_in_error: "Ошибка входа. Попробуйте снова.",
      logout: "Выйти",
    },
    notification: {
      updated: "Обновлено |||| Обновлено элементов: %{smart_count}",
      created: "Создано",
      deleted: "Удалено |||| Удалено элементов: %{smart_count}",
      bad_item: "Некорректный элемент",
      item_doesnt_exist: "Элемент не найден",
      http_error: "Ошибка связи с сервером",
      data_provider_error: "Ошибка загрузки данных. Подробности в консоли.",
      i18n_error: "Не удалось загрузить переводы",
      canceled: "Действие отменено",
      logged_out: "Сессия завершена. Войдите снова.",
      not_authorized: "Недостаточно прав для доступа.",
      application_update_available: "Доступна новая версия.",
      offline: "Нет соединения. Данные не загружены.",
    },
    validation: {
      required: "Обязательное поле",
      minLength: "Минимум %{min} символов",
      maxLength: "Максимум %{max} символов",
      minValue: "Не меньше %{min}",
      maxValue: "Не больше %{max}",
      number: "Должно быть числом",
      email: "Некорректный email",
      oneOf: "Допустимые значения: %{options}",
      regex: "Формат не совпадает: %{pattern}",
      unique: "Должно быть уникальным",
    },
    saved_queries: {
      label: "Сохранённые запросы",
      query_name: "Название запроса",
      new_label: "Сохранить текущий запрос…",
      new_dialog_title: "Сохранить запрос как",
      remove_label: "Удалить сохранённый запрос",
      remove_label_with_name: "Удалить запрос «%{name}»",
      remove_dialog_title: "Удалить сохранённый запрос?",
      remove_message: "Удалить этот запрос из списка?",
      help: "Отфильтруйте список и сохраните запрос",
    },
    configurable: {
      customize: "Настроить",
      configureMode: "Настройка страницы",
      inspector: {
        title: "Инспектор",
        content: "Наведите на элемент, чтобы настроить",
        reset: "Сбросить настройки",
        hideAll: "Скрыть все",
        showAll: "Показать все",
      },
      Datagrid: {
        title: "Таблица",
        unlabeled: "Столбец без названия #%{column}",
      },
      SimpleForm: {
        title: "Форма",
        unlabeled: "Поле без названия #%{input}",
      },
      SimpleList: {
        title: "Список",
        primaryText: "Основной текст",
        secondaryText: "Дополнительный текст",
        tertiaryText: "Третий текст",
      },
    },
  },
  "ra-supabase": {
    auth: {
      email: "Email",
      confirm_password: "Подтвердите пароль",
      sign_in_with: "Войти через %{provider}",
      forgot_password: "Забыли пароль?",
      reset_password: "Сбросить пароль",
      password_reset:
        "Проверьте почту: отправлено письмо со ссылкой для сброса пароля.",
      missing_tokens: "Нет токенов доступа",
      back_to_login: "Вернуться к входу",
    },
    reset_password: {
      forgot_password: "Забыли пароль?",
      forgot_password_details: "Введите email для инструкций.",
    },
    set_password: {
      new_password: "Задайте пароль",
    },
    validation: {
      password_mismatch: "Пароли не совпадают",
    },
  },
  resources: {
    contacts: {
      name: "Контакт",
      fields: {},
    },
    companies: {
      name: "Компания",
      fields: {},
    },
    deals: {
      name: "Сделка",
      fields: {},
    },
    sales: {
      name: "Пользователь",
      fields: {},
    },
    teams: {
      name: "Команда",
      fields: {},
    },
    sprints: {
      name: "Спринт",
      fields: {},
    },
    tasks: {
      name: "Задача",
      fields: {},
    },
    tags: {
      name: "Тег",
      fields: {},
    },
    configuration: {
      name: "Настройки",
      fields: {},
    },
    contact_notes: {
      name: "Заметка (контакт)",
      fields: {},
    },
    deal_notes: {
      name: "Заметка (сделка)",
      fields: {},
    },
  },
  crm: {
    nav: {
      dashboard: "Главная",
      contacts: "Контакты",
      companies: "Компании",
      deals: "Сделки",
      teams: "Команды",
      sprints: "Спринты",
      review_360: "360°",
      tasks: "Задачи",
      users: "Пользователи",
      settings: "Настройки",
      profile: "Профиль",
      import_data: "Импорт данных",
    },
    home: "Главная",
    new_contact: "Новый контакт",
    new_company: "Новая компания",
    new_deal: "Новая сделка",
    new_team: "Новая команда",
    new_sprint: "Новый спринт",
    new_user: "Новый пользователь",
    create_company: "Создать компанию",
    create_deal: "Создать сделку",
    edit_company: "Изменить компанию",
    show_company: "Компания",
    edit_contact: "Изменить контакт",
    show_contact: "Просмотр контакта",
    no_companies: "Компаний пока нет.",
    no_companies_hint: "Похоже, список компаний пуст.",
    no_deals: "Сделок не найдено",
    no_deals_hint: "Добавьте сделку или перейдите к контакту.",
    no_deals_filter_hint: "Измените фильтры или добавьте сделку.",
    add_first_contact_before_deal: "Сначала добавьте первый контакт, затем создайте сделку.",
    add_first_contact_link: "Добавить первый контакт",
    no_teams: "Команд пока нет.",
    no_teams_hint: "Создайте команду, чтобы добавлять участников и привязывать к спринтам.",
    no_sprints: "Спринтов пока нет.",
    no_sprints_hint: "Создайте спринт и назначьте команды или участников.",
    hot_contacts: "Горячие контакты",
    hot_contacts_hint: 'Здесь отображаются контакты со статусом «горячий».',
    hot_contacts_empty_extra: "Измените статус контакта, добавив заметку и нажав «Показать опции».",
    create_contact: "Создать контакт",
    deals_pipeline: "Воронка сделок",
    whats_next: "Что дальше?",
    step_done: "выполнено",
    install_crm: "Установлен Atomic CRM",
    add_first_contact: "Добавьте первый контакт",
    add_first_note: "Добавьте первую заметку",
    go_to_contact_add_note: "Перейдите в контакт и добавьте заметку",
    add_note: "Добавить заметку",
    company: "Компания",
    contact: "Контакт",
    category: "Категория",
    description: "Описание",
    members: "Участники",
    direct_participants: "Участники (назначены напрямую)",
    assigned_teams: "Назначенные команды",
    details: "Детали",
    members_count: "Участники",
    create_note: "Создать заметку",
    create_note_for: "Создать заметку для",
    note_added: "Заметка добавлена",
    task_deleted: "Задача удалена",
    import: "Импорт",
    import_contacts: "Импорт контактов",
    mark_done: "Выполнено",
    mark_undone: "Не выполнено",
    delete_task: "Удалить задачу",
    no_contacts: "Нет контактов",
    add_contact: "Контакт",
    add_note_short: "Заметка",
    add_task: "Задача",
    system_theme: "Системная",
    light_theme: "Светлая",
    dark_theme: "Тёмная",
    user_created: "Пользователь создан. Он получит письмо для установки пароля.",
    user_updated: "Пользователь обновлён",
    error_occurred: "Произошла ошибка. Попробуйте снова.",
    error_creating_user: "Ошибка при создании пользователя.",
    no_contacts_company: "Нет контактов",
    contacts_count: "Контактов",
    administrator: "Админ",
    disabled: "Отключён",
    you: "Вы",
    details: "Детали",
    members: "Участники",
    participants: "Участники",
    name: "Название",
    description: "Описание",
    status: "Статус",
    start_date: "Дата начала",
    end_date: "Дата окончания",
    goal: "Цель",
    source: "Источник",
    direct: "Напрямую",
    team: "Команда",
    no_members: "В этой команде пока нет участников.",
    no_participants: "В этом спринте пока нет участников.",
    failed_to_load_members: "Не удалось загрузить участников.",
    failed_to_load_participants: "Не удалось загрузить участников.",
    planned: "Запланирован",
    active: "Активен",
    completed: "Завершён",
    feedback: "Оценка участников",
  },
};

export default ru;
