-- Teams and sprints for development planning.
-- Teams store members, sprints can have both direct members and assigned teams.
-- Additional views provide convenient participant APIs.

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "member_ids" bigint[] not null default '{}'::bigint[],
    "sales_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    constraint "teams_pkey" primary key ("id")
);

create table "public"."sprints" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "goal" text,
    "status" text not null default 'planned',
    "start_date" date not null,
    "end_date" date not null,
    "team_ids" bigint[] not null default '{}'::bigint[],
    "member_ids" bigint[] not null default '{}'::bigint[],
    "sales_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    constraint "sprints_pkey" primary key ("id"),
    constraint "sprints_status_check" check ("status" in ('planned', 'active', 'completed')),
    constraint "sprints_dates_check" check ("start_date" <= "end_date")
);

alter table "public"."teams" enable row level security;
alter table "public"."sprints" enable row level security;

alter table "public"."teams"
  add constraint "teams_sales_id_fkey"
  foreign key ("sales_id") references "public"."sales"("id") on update cascade on delete set null;

alter table "public"."sprints"
  add constraint "sprints_sales_id_fkey"
  foreign key ("sales_id") references "public"."sales"("id") on update cascade on delete set null;

create trigger set_teams_sales_id_trigger
before insert on "public"."teams"
for each row execute function set_sales_id_default();

create trigger set_sprints_sales_id_trigger
before insert on "public"."sprints"
for each row execute function set_sales_id_default();

-- Convenient list of users in each team.
create or replace view "public"."team_members"
with (security_invoker = on)
as
select
  (t.id::text || '-' || s.id::text) as id,
  t.id as team_id,
  s.id as sales_id,
  s.first_name,
  s.last_name,
  s.email,
  s.avatar,
  s.administrator,
  s.disabled
from "public"."teams" t
join lateral unnest(coalesce(t.member_ids, '{}'::bigint[])) as member_id on true
join "public"."sales" s on s.id = member_id;

-- Convenient list of all sprint participants (direct + from assigned teams).
create or replace view "public"."sprint_participants"
with (security_invoker = on)
as
with direct_members as (
  select
    sp.id as sprint_id,
    member_id as sales_id,
    null::bigint as source_team_id,
    'direct'::text as source_type
  from "public"."sprints" sp
  join lateral unnest(coalesce(sp.member_ids, '{}'::bigint[])) as member_id on true
),
team_members_expanded as (
  select
    sp.id as sprint_id,
    tm.sales_id,
    tm.team_id as source_team_id,
    'team'::text as source_type
  from "public"."sprints" sp
  join lateral unnest(coalesce(sp.team_ids, '{}'::bigint[])) as assigned_team_id on true
  join "public"."team_members" tm on tm.team_id = assigned_team_id
),
all_participants as (
  select * from direct_members
  union
  select * from team_members_expanded
),
ranked as (
  select
    ap.*,
    row_number() over (
      partition by ap.sprint_id, ap.sales_id
      order by case when ap.source_type = 'direct' then 0 else 1 end
    ) as rn
  from all_participants ap
)
select
  (r.sprint_id::text || '-' || r.sales_id::text) as id,
  r.sprint_id,
  r.sales_id,
  s.first_name,
  s.last_name,
  s.email,
  s.avatar,
  s.administrator,
  s.disabled,
  r.source_team_id,
  t.name as source_team_name,
  r.source_type
from ranked r
join "public"."sales" s on s.id = r.sales_id
left join "public"."teams" t on t.id = r.source_team_id
where r.rn = 1;

grant select, insert, update, delete on "public"."teams" to "authenticated";
grant select, insert, update, delete on "public"."sprints" to "authenticated";
grant select on "public"."team_members" to "authenticated";
grant select on "public"."sprint_participants" to "authenticated";

grant select, insert, update, delete on "public"."teams" to "service_role";
grant select, insert, update, delete on "public"."sprints" to "service_role";
grant select on "public"."team_members" to "service_role";
grant select on "public"."sprint_participants" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."teams"
as permissive
for select
to authenticated
using (true);

create policy "Enable insert for authenticated users only"
on "public"."teams"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on "public"."teams"
as permissive
for update
to authenticated
using (true)
with check (true);

create policy "Team Delete Policy"
on "public"."teams"
as permissive
for delete
to authenticated
using (true);

create policy "Enable read access for authenticated users"
on "public"."sprints"
as permissive
for select
to authenticated
using (true);

create policy "Enable insert for authenticated users only"
on "public"."sprints"
as permissive
for insert
to authenticated
with check (true);

create policy "Enable update for authenticated users only"
on "public"."sprints"
as permissive
for update
to authenticated
using (true)
with check (true);

create policy "Sprint Delete Policy"
on "public"."sprints"
as permissive
for delete
to authenticated
using (true);
