-- 1) Task feedback: отзыв по коллеге в рамках задачи (кнопка/href для интеграции в любую CRM)
-- 2) 180°: отзыв в профиле сотрудника (свободный текст + плюсы/минусы)
-- 3) 360°: годовая кампания, менеджер создаёт → публикация → рандомные назначения (3 отзыва на человека), ответы на вопросы

-- Task feedback (в контексте задачи)
create table "public"."task_feedbacks" (
  "id" bigint generated by default as identity not null,
  "task_id" bigint not null,
  "reviewer_sales_id" bigint not null,
  "reviewee_sales_id" bigint not null,
  "sprint_id" bigint,
  "content" text not null,
  "sales_id" bigint,
  "created_at" timestamp with time zone not null default now(),
  constraint "task_feedbacks_pkey" primary key ("id"),
  constraint "task_feedbacks_task_id_fkey" foreign key ("task_id") references "public"."tasks"("id") on delete cascade,
  constraint "task_feedbacks_reviewer_sales_id_fkey" foreign key ("reviewer_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "task_feedbacks_reviewee_sales_id_fkey" foreign key ("reviewee_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "task_feedbacks_sprint_id_fkey" foreign key ("sprint_id") references "public"."sprints"("id") on delete set null
);

-- 180° review (в профиле сотрудника: свободный текст + плюсы/минусы)
create table "public"."reviews_180" (
  "id" bigint generated by default as identity not null,
  "reviewee_sales_id" bigint not null,
  "reviewer_sales_id" bigint not null,
  "free_text" text not null,
  "good_points" text[] not null default '{}',
  "bad_points" text[] not null default '{}',
  "sales_id" bigint,
  "created_at" timestamp with time zone not null default now(),
  constraint "reviews_180_pkey" primary key ("id"),
  constraint "reviews_180_reviewee_sales_id_fkey" foreign key ("reviewee_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "reviews_180_reviewer_sales_id_fkey" foreign key ("reviewer_sales_id") references "public"."sales"("id") on delete cascade
);

-- 360° campaign (раз в год, создаётся менеджером)
create table "public"."review_360_campaigns" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "year" smallint not null,
  "status" text not null default 'draft' check ("status" in ('draft', 'published')),
  "created_by_sales_id" bigint,
  "published_at" timestamp with time zone,
  "sales_id" bigint,
  "created_at" timestamp with time zone not null default now(),
  constraint "review_360_campaigns_pkey" primary key ("id"),
  constraint "review_360_campaigns_created_by_sales_id_fkey" foreign key ("created_by_sales_id") references "public"."sales"("id") on delete set null
);

-- 360° assignment: кому кого оценивать (система выбирает 3–4 сотрудников на каждого ревьюера)
create table "public"."review_360_assignments" (
  "id" bigint generated by default as identity not null,
  "campaign_id" bigint not null,
  "reviewer_sales_id" bigint not null,
  "reviewee_sales_id" bigint not null,
  "status" text not null default 'pending' check ("status" in ('pending', 'submitted')),
  "sales_id" bigint,
  "created_at" timestamp with time zone not null default now(),
  constraint "review_360_assignments_pkey" primary key ("id"),
  constraint "review_360_assignments_campaign_id_fkey" foreign key ("campaign_id") references "public"."review_360_campaigns"("id") on delete cascade,
  constraint "review_360_assignments_reviewer_sales_id_fkey" foreign key ("reviewer_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "review_360_assignments_reviewee_sales_id_fkey" foreign key ("reviewee_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "review_360_assignments_uniq" unique ("campaign_id", "reviewer_sales_id", "reviewee_sales_id")
);

-- 360° answers: ответы на вопросы по назначению (отзыв о reviewee от reviewer)
create table "public"."review_360_answers" (
  "id" bigint generated by default as identity not null,
  "assignment_id" bigint not null,
  "reviewee_sales_id" bigint not null,
  "answers" jsonb not null default '[]',
  "submitted_at" timestamp with time zone not null default now(),
  constraint "review_360_answers_pkey" primary key ("id"),
  constraint "review_360_answers_assignment_id_fkey" foreign key ("assignment_id") references "public"."review_360_assignments"("id") on delete cascade,
  constraint "review_360_answers_reviewee_sales_id_fkey" foreign key ("reviewee_sales_id") references "public"."sales"("id") on delete cascade,
  constraint "review_360_answers_assignment_uniq" unique ("assignment_id")
);

alter table "public"."task_feedbacks" enable row level security;
alter table "public"."reviews_180" enable row level security;
alter table "public"."review_360_campaigns" enable row level security;
alter table "public"."review_360_assignments" enable row level security;
alter table "public"."review_360_answers" enable row level security;

create trigger set_task_feedbacks_sales_id_trigger before insert on "public"."task_feedbacks" for each row execute function set_sales_id_default();
create trigger set_reviews_180_sales_id_trigger before insert on "public"."reviews_180" for each row execute function set_sales_id_default();
create trigger set_review_360_campaigns_sales_id_trigger before insert on "public"."review_360_campaigns" for each row execute function set_sales_id_default();
create trigger set_review_360_assignments_sales_id_trigger before insert on "public"."review_360_assignments" for each row execute function set_sales_id_default();

-- RLS: authenticated read/write (admin/manager visibility можно уточнить отдельно)
create policy "task_feedbacks_select" on "public"."task_feedbacks" for select to authenticated using (true);
create policy "task_feedbacks_insert" on "public"."task_feedbacks" for insert to authenticated with check (true);
create policy "task_feedbacks_update" on "public"."task_feedbacks" for update to authenticated using (true) with check (true);
create policy "task_feedbacks_delete" on "public"."task_feedbacks" for delete to authenticated using (true);

create policy "reviews_180_select" on "public"."reviews_180" for select to authenticated using (true);
create policy "reviews_180_insert" on "public"."reviews_180" for insert to authenticated with check (true);
create policy "reviews_180_update" on "public"."reviews_180" for update to authenticated using (true) with check (true);
create policy "reviews_180_delete" on "public"."reviews_180" for delete to authenticated using (true);

create policy "review_360_campaigns_select" on "public"."review_360_campaigns" for select to authenticated using (true);
create policy "review_360_campaigns_insert" on "public"."review_360_campaigns" for insert to authenticated with check (true);
create policy "review_360_campaigns_update" on "public"."review_360_campaigns" for update to authenticated using (true) with check (true);
create policy "review_360_campaigns_delete" on "public"."review_360_campaigns" for delete to authenticated using (true);

create policy "review_360_assignments_select" on "public"."review_360_assignments" for select to authenticated using (true);
create policy "review_360_assignments_insert" on "public"."review_360_assignments" for insert to authenticated with check (true);
create policy "review_360_assignments_update" on "public"."review_360_assignments" for update to authenticated using (true) with check (true);
create policy "review_360_assignments_delete" on "public"."review_360_assignments" for delete to authenticated using (true);

create policy "review_360_answers_select" on "public"."review_360_answers" for select to authenticated using (true);
create policy "review_360_answers_insert" on "public"."review_360_answers" for insert to authenticated with check (true);
create policy "review_360_answers_update" on "public"."review_360_answers" for update to authenticated using (true) with check (true);
create policy "review_360_answers_delete" on "public"."review_360_answers" for delete to authenticated using (true);

grant select, insert, update, delete on "public"."task_feedbacks" to authenticated;
grant select, insert, update, delete on "public"."reviews_180" to authenticated;
grant select, insert, update, delete on "public"."review_360_campaigns" to authenticated;
grant select, insert, update, delete on "public"."review_360_assignments" to authenticated;
grant select, insert, update, delete on "public"."review_360_answers" to authenticated;

grant select, insert, update, delete on "public"."task_feedbacks" to service_role;
grant select, insert, update, delete on "public"."reviews_180" to service_role;
grant select, insert, update, delete on "public"."review_360_campaigns" to service_role;
grant select, insert, update, delete on "public"."review_360_assignments" to service_role;
grant select, insert, update, delete on "public"."review_360_answers" to service_role;

-- Публикация 360: создаёт назначения — у каждого сотрудника 3 ревьюера (из той же команды / общих спринтов по возможности)
create or replace function "public"."review_360_create_assignments"(p_campaign_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  reviewee_id bigint;
  candidate_ids bigint[];
  chosen bigint[];
  idx int;
  n_cand int;
  reviewee_ids bigint[];
begin
  select array_agg(s.id order by s.id) into reviewee_ids from sales s where s.disabled = false;
  if reviewee_ids is null or array_length(reviewee_ids, 1) < 2 then
    return;
  end if;

  foreach reviewee_id in array reviewee_ids
  loop
    -- Кандидаты: одна команда или общий спринт с reviewee
    candidate_ids := array(
      select distinct other.id
      from sales other
      where other.id <> reviewee_id and other.disabled = false
      and (
        exists (
          select 1 from teams t
          where reviewee_id = any(t.member_ids) and other.id = any(t.member_ids)
        )
        or exists (
          select 1 from sprint_participants a
          join sprint_participants b on a.sprint_id = b.sprint_id and b.sales_id = other.id
          where a.sprint_id = b.sprint_id and a.sales_id = reviewee_id
        )
      )
    );
    if array_length(candidate_ids, 1) is null or array_length(candidate_ids, 1) = 0 then
      candidate_ids := array(select s.id from sales s where s.id <> reviewee_id and s.disabled = false);
    end if;

    -- Случайно выбрать до 3 разных ревьюеров (shuffle и взять первые 3)
    candidate_ids := (select array_agg(x order by random()) from unnest(candidate_ids) x);
    n_cand := least(3, coalesce(array_length(candidate_ids, 1), 0));
    for idx in 1..n_cand loop
      insert into review_360_assignments (campaign_id, reviewer_sales_id, reviewee_sales_id, status)
      values (p_campaign_id, candidate_ids[idx], reviewee_id, 'pending')
      on conflict (campaign_id, reviewer_sales_id, reviewee_sales_id) do nothing;
    end loop;
  end loop;
end;
$$;
